from pathlib import Path
import hashlib,json,shutil,tarfile
b=Path(__file__).resolve().parent;release=b.parent/'release';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
image=b/'cambium_xv2-21x-cheetah-2026.10.02.13-sysupgrade.bin';assert image.exists()
checks=['extracted-package-tests.json','hardware-fit.json','managed12-command-tests.json','managed12-validator-tests.json','ram-copy-tests.json']
for n in checks:assert json.loads((b/n).read_text())['passed'],n
assert 'PASS: four complete target compilations' in (b/'target-package-tests.log').read_text()
assert 'VERIFY_EXIT=0' in (b/'verification.log').read_text()
meta=json.loads((b/'image-metadata.json').read_text());assert meta['supported_devices']==['cambiumnetworks,xv2-21x'] and meta['compat_version']=='1.0' and meta['est_supported']==1
version='cheetah-2026.10.02.13';out=release/'cheetah-openwifi-2026.10.02.13';assert not out.exists();out.mkdir();(out/'evidence').mkdir();(out/'sources').mkdir();shutil.copy2(image,out/image.name)
for p in b.iterdir():
 if p.is_file() and p.suffix in ['.json','.log']:shutil.copy2(p,out/'evidence'/p.name)
for p in b.iterdir():
 if p.is_file() and p.name in ['verify.sh','check-image.py','adapt-tests.py','package.py','source-changes.patch','source-publication.bundle']:shutil.copy2(p,out/'sources'/p.name)
shared=b.parent.parent/'shared-discovery-fix';(out/'evidence/source-qualified').mkdir()
for n in ['SOURCE-RECEIPT.txt','discovery-renewal-regressions.json','discovery-renewal-crypto.json','discovery-est-boundaries.json']:shutil.copy2(shared/n,out/'evidence/source-qualified'/n)
shutil.copytree(shared/'package',out/'sources/cloud_discovery-release6')
receipt=json.loads((b/'extracted-package-tests.json').read_text());tip=(b/'image-verification.log').read_text().split('FULL_REVISION=')[1].splitlines()[0];assert 'TIP-cheetah-2026.10.02.13-4a893a76' in tip
manifest=dict(family='Cheetah',version=version,full_reported_revision=tip,source_commit='4a893a76f505bfa687b9e4fa2aaddf00cf7cbb6a',source_branch='cheetah-discovery-renewal',source_tag=version,corrected_parent_commit='7d9a8b29269fdb9b29c64910844ed9a380f303e9',canonical_discovery_commit='a631587a322f15f12dbacfba079be37acfaabf3f',identity='Phil Taylor <phil@m0vse.uk>',openwrt_base_commit='7b849a21e1d73c6b38122357dc87e5fd6d285bcd',openwrt_base_is_pristine=False,target='qualcommax/ipq50xx',architecture='aarch64_cortex-a53',kernel='6.12.85',qualified_models=['XV2-21X'],model_compat_map={'XV2-21X':'cambium_xv2-21x'},sku=35,unqualified_models=['XV2-22H','XV2-23T'],excluded_models=['E600'],image=dict(filename=image.name,bytes=image.stat().st_size,sha256=sha(image),metadata=meta),package_versions=receipt['package_versions'],fresh_tests={n:json.loads((b/n).read_text()).get('count',len(json.loads((b/n).read_text()).get('cases',[]))) for n in checks},target_runtime_controls=7,source_tests_reused={'daemon_policy':35,'openssl_crypto':9,'est_persistence_boundaries':11},upgrade={'normal_confirmed_12_managed_preserving':True,'replacement_bridge_from_12_required':False,'unmodified_11_requires_existing_tr_bridge':True,'older_operator_source_ledgers_not_autoenrolled_for_new_est_script':True},private_PKI_activation=False,ap_actions='none',publication='pending coordinator',limitations=['no live EST/controller reauthentication','no physical UBI persistence/power-loss test','per-file atomic renames are not a multi-file power-loss transaction','gateway rollback is in-session, not daemon-crash journal'])
(out/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
(out/'README.txt').write_text('''Cheetah .13 discovery renewal fix\n\nQualified XV2-21X only, SKU35. Published .11/.12 firmware bytes and original provenance are unchanged. Source is based on tree-identical corrected .12 ancestry, with Phil Taylor <phil@m0vse.uk> identity; only canonical cloud_discovery package release6 and its source tests were integrated.\n\nThe operational renewal window is 90 days rather than one year; the Demo three-day window remains. Failed renewal preserves the working client, gateway and identity and returns failure. Replacement leaves require current configured CA trust, validity, the existing key and full subject match. Staging/persistence failures propagate before runtime activation. Existing allowed-controller policy, ready flash/local pins and default-disabled private ownership guards remain. This image does not install or activate private PKI, does not provision new EST trust, and does not silently send manual/private issuers to public OpenLAN EST.\n\nFresh actual extracted-image checks verify release6 and exact daemon/EST/policy/init bytes, absence of private-PKI helper activation, and byte-identical .12 DFS health/healer, A/B helpers, certificate snapshot, managed upgrade command and tr-retaining platform. Seven actual AArch64 target compilation/import/missing-leaf/private-guard controls pass in a private mount namespace. Normal confirmed .12 managed command archive is tested in all four keep-flag combinations; actual .12 validators/EST and retained-only RAM extraction accept the new .13 image with compatibility1.0 and qualified model checks. No replacement outgoing bridge is required from unmodified confirmed .12. Unmodified .11 still requires its previously qualified outgoing tr bridge before normal controller upgrade. Old image-pinned operator wrappers must not be relabeled or assumed to approve the new release6 EST implementation.\n\nShared source receipts are reused explicitly:35 daemon/reenroll/policy,9 synthetic real OpenSSL crypto,11 EST selection/persistence boundary cases, plus package policy/DHCP/lease regressions in SOURCE-RECEIPT.txt. .12 DFS/hardware qualification is retained by exact source and unchanged shipped-byte checks; it was not rerun as a new physical qualification. Fresh root/FIT/model/partition/calibration checks are included. No AP operations, live EST, controller reauthentication, physical UBI persistence or power-loss proof. Individual atomic file renames are not a multi-file power-loss transaction; previous gateway rollback is in-memory within the daemon session.\n''')
files=sorted(p for p in out.rglob('*') if p.is_file() and p.name!='SHA256SUMS');(out/'SHA256SUMS').write_text(''.join(sha(p)+'  '+str(p.relative_to(out))+'\n' for p in files));archive=release/(out.name+'.tar.gz')
with tarfile.open(archive,'w:gz') as t:t.add(out,arcname=out.name)
handoff=dict(version=version,source_commit=manifest['source_commit'],source_parent=manifest['corrected_parent_commit'],image=manifest['image'],bundle=out.name,archive=archive.name,archive_bytes=archive.stat().st_size,archive_sha256=sha(archive),files=len(files),publication='pending coordinator',ap_actions='none',normal_confirmed_12_preserving_upgrade=True)
(release/'discovery13-handoff.json').write_text(json.dumps(handoff,indent=2)+'\n');print(json.dumps(handoff,indent=2))
