#!/bin/sh /etc/rc.common
START=78
USE_PROCD=1

start_service() {
	[ "$(uci -q get radio-crash.main.enabled)" = 1 ] || return 0
	procd_open_instance
	procd_set_param command /usr/libexec/ucentral-radio-crash-dispatch watch
	procd_set_param respawn 3600 5 0
	procd_close_instance
}
