from pathlib import Path
import hashlib,json,shutil,tarfile
b=Path(__file__).resolve().parent;release=b.parent/'release';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
image=b/'cambium_xv2-21x-cheetah-2026.10.02.12-sysupgrade.bin';digest='819bcef819df28c71d1a40d27c682dd2756a8386ac4c30ab4fc7f0e1ef3c5bc1'
assert sha(image)==digest and image.stat().st_size==29727028
assert 'VERIFY_EXIT=0' in (b/'dfs12-verification.log').read_text()
checks=['built-image-tests.json','target-cli-tests.json','managed11-validator-tests.json','ram-copy-tests.json','dfs12-unit-tests.json','dfs12-subprocess-tests.json','dfs12-health-healing-tests.json','dfs12-managed11-command-tests.json','hardware-fit.json','kernel-header-audit.json']
for n in checks:assert json.loads((b/n).read_text())['passed'],n
metadata=json.loads((b/'image-metadata.json').read_text());assert metadata['compat_version']=='1.0' and metadata['est_supported']==1
source='e43b567422c03225824fcfae178fd3254ab1aba1';tip=json.loads((b/'built-image-tests.json').read_text())['tip_metadata'];assert 'TIP-cheetah-2026.10.02.12-e43b5674' in tip
firmware=release/'cheetah-openwifi-2026.10.02.12';assert not firmware.exists();firmware.mkdir();(firmware/'evidence').mkdir();(firmware/'sources').mkdir()
shutil.copy2(image,firmware/image.name)
for p in b.glob('*'):
 if p.is_file() and p.suffix in ['.json','.log']:shutil.copy2(p,firmware/'evidence'/p.name)
for n in ['source-changes.patch','verify.sh','adapt-tests.py','package.py']:shutil.copy2(b/n,firmware/'sources'/n)
for p in (b.parent.parent/'openwifi-dfs-health/source').rglob('*'):
 if p.is_file():dst=firmware/'sources'/p.relative_to(b.parent.parent/'openwifi-dfs-health/source');dst.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,dst)
manifest=dict(family='Cheetah',version='cheetah-2026.10.02.12',full_reported_revision='OpenWrt 25.12.3 r32912-6639b15f62 / TIP-cheetah-2026.10.02.12-e43b5674',source_commit=source,source_branch='cheetah-dfs',source_tag='cheetah-2026.10.02.12',canonical_dfs_commit='e3ea012ee0239b2a356855435b2340e5adfa410f',source_publication='private build branch/tag; coordinator publication pending',openwrt_base_commit='7b849a21e1d73c6b38122357dc87e5fd6d285bcd',openwrt_base_is_pristine=False,build_config_sha256='3fd6f7865551efa9fbbf6c9155c89c1262ae4e6fcb18fcfeac99602cd8415d46',target='qualcommax/ipq50xx',architecture='aarch64_cortex-a53',kernel='6.12.85',qualified_models=['XV2-21X'],model_compat_map={'XV2-21X':'cambium_xv2-21x'},sku=35,unqualified_models=['XV2-22H','XV2-23T'],excluded_models=['E600'],fit_config='config@mp03.3-ocelot',image=dict(filename=image.name,bytes=image.stat().st_size,sha256=digest,metadata=metadata),actual_dfs_packages=json.loads((b/'built-image-tests.json').read_text())['package_versions'],dfs_shipped_sources={n:sha(b.parent.parent/'openwifi-dfs-health/source'/p) for n,p in [('dfs_cac.uc','system/dfs_cac.uc'),('health.uc','system/health.uc'),('ucentral-state','ucentral-state')]},fresh_tests={n:json.loads((b/n).read_text()).get('count',json.loads((b/n).read_text()).get('objects_checked',len(json.loads((b/n).read_text()).get('cases',[])))) for n in checks},upgrade=dict(from_tip_minimum='2026.10.02.11',managed_command_archive_flags=4,actual_outgoing_validator_cases=28,unmodified_11_requires_outgoing_tr_bridge=True,new_12_platform_retains_tr=True,new_12_satisfies_existing_preserve_r6_implementation_and_runtime_contract=True),hardware_acceptance='pending operator actual DFS/CAC completion and preserving-bank test',ap_actions='none')
(firmware/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
notes='''Cheetah .12 DFS CAC-aware health candidate\n\nOnly qualified XV2-21X, SKU35. Exact revision: OpenWrt 25.12.3 r32912-6639b15f62 / TIP-cheetah-2026.10.02.12-e43b5674. .11 and existing installers remain immutable.\n\nCanonical e3ea012e health/self-healer policy checks fresh hostapd global STATUS and exact current netifd/UCI interface, configured SSID and sysfs PHY. Suppress only positively active CAC: state DFS, positive numeric remaining not exceeding reported duration. No channel exemption, cached grace or regulatory-duration ceiling. Aborted/expired/unavailable/malformed evidence retains ordinary failure detection; independent radio/SSID/RADIUS/DHCP/DNS faults retain existing behavior. Standard hostapd-utils and coreutils-timeout dependencies are shipped. Dynamic require('dfs_cac') with underscore name is tested using the exact production search path on actual target ucode; both complete health/state scripts compile. Actual target timeout kills command and child.\n\nUpgrade from confirmed unmodified .11 requires an authenticated outgoing tr bridge BEFORE normal controller upgrade: .11's outgoing RAM list lacks tr, and incoming .12 cannot repair the old copy list. The separate .12-pinned preserving-r7 installer installs that exact reviewed bridge then invokes explicit private sysupgrade -f, preserving rendered config, shadow baseline, active document, identity and endpoint policy. Its --check must pass on the AP before an operator chooses --install. If using normal managed UI after the bridge, the actual .11 cmd_upgrade.uc archive/flags were tested in four keep-flag combinations and always use full -f archive; real .11 firmware validators accept .12 at configuration compatibility1.0 and refuse incompatible/model/EST cases. No -n or -F on the preserving route. .12 retains tr itself, so its future managed upgrades have the required copied tool. Stock conversion remains the separate qualified stock-clean route; this artifact does not authorize importing stock identity.\n\nFresh offline tests: 42 classifier/mapping controls, 5 bounded subprocess controls, 23 actual health/healer function controls, 8 actual extracted-image source/package/target compile/dynamic require/timeout assertions, 2 actual target CLI STATUS-only socket controls, 4 .11 managed command archive cases, 28 actual .11 validator/EST cases against .12, 4 retained-only RAM extraction controls, complete root/FIT/board/calibration/partition checks and 98 kernel-header object checks. Hardware, netifd/sysfs, UBI and network boundaries are private fixtures; no AP daemon, enrollment, configuration, mount, flash, reboot or radio operation was run. These receipts do not establish physical CAC completion or power-loss/RAM-pivot acceptance on Cheetah.\n'''
(firmware/'README.txt').write_text(notes)
prior=release/'operator-cheetah-openwifi-preserve-minimum-2026.10.02.11-r6';operator=release/'operator-cheetah-openwifi-preserve-minimum-2026.10.02.12-r7';assert not operator.exists();shutil.copytree(prior,operator)
old_image=operator/(operator/'IMAGE').read_text().strip();old_image.unlink();shutil.copy2(image,operator/image.name);(operator/'IMAGE').write_text(image.name+'\n')
# Incoming payload is byte-identical to r6's preserving bridge (including tr).
for n in ['cambium-ab.sh','cambium-ab-upgrade.sh','cambium-ab-certificates.sh','platform.sh','modules/cambium-ab-cheetah.sh']:assert (operator/n).read_bytes()==(b/'payload'/n).read_bytes(),n
(operator/'README-installer.txt').write_text(notes+'\nRun sh cheetah-sysupgrade-preserve.sh --check, then choose --install only after live qualification passes. Minimum TIP release remains 2026.10.02.11; newer metadata requires the approved whole implementation/runtime contract. A pending bridge is repaired only from authenticated original/staged states with code/tool gates, never restoring release metadata; invalid release prevents new upgrade. The underlying installer code and approval ledger are byte-identical to sealed r6. Its 87 wrapper,32 transaction,33 recovery refusal,34 metadata/script,22 runtime and18 metadata-independent recovery controls are inherited r6 evidence. Fresh .12 image/actual outgoing validators/managed command/RAM and DFS receipts are included separately.\n')
for p in (firmware/'evidence').iterdir():shutil.copy2(p,operator/'evidence'/('dfs12-'+p.name))
shutil.copy2(b/'source-changes.patch',operator/'sources/dfs12-source-changes.patch')
m=json.loads((operator/'manifest.json').read_text());m.update(operator_revision=7,version=manifest['version'],full_reported_revision=manifest['full_reported_revision'],source_commit=source,image=manifest['image'],firmware_unchanged=False,supersedes=prior.name,dfs_target_packages=manifest['actual_dfs_packages'],fresh_dfs12_tests=manifest['fresh_tests'],installer_policy='byte-identical r6 preserving/minimum/recovery code and approved ledger; only target IMAGE/manifest/evidence updated')
(operator/'manifest.json').write_text(json.dumps(m,indent=2)+'\n')
receipts=[]
for out in [firmware,operator]:
 files=sorted(p for p in out.rglob('*') if p.is_file() and p.name!='SHA256SUMS');(out/'SHA256SUMS').write_text(''.join(sha(p)+'  '+str(p.relative_to(out))+'\n' for p in files));archive=release/(out.name+'.tar.gz')
 with tarfile.open(archive,'w:gz') as t:t.add(out,arcname=out.name)
 receipts.append(dict(bundle=out.name,archive=archive.name,archive_sha256=sha(archive),archive_bytes=archive.stat().st_size,files=len(files)))
receipt=dict(version=manifest['version'],source_commit=source,image=manifest['image'],artifacts=receipts,publication='pending coordinator',ap_actions='none',requires_outgoing_tr_bridge_from_unmodified_11=True)
(release/'dfs12-handoff.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt,indent=2))
