#!/bin/sh /etc/rc.common
START=19
USE_PROCD=1
start_service() {
	[ "$(cat /tmp/sysinfo/board_name 2>/dev/null)" = cambiumnetworks,xv2-2t1 ] || return 0
	procd_open_instance
	procd_set_param command /usr/libexec/ucentral-network-trace
	procd_close_instance
}
